"use strict";

const CONFIG={
  endpoint:"https://script.google.com/macros/s/AKfycbzsKJFK_ztq0-jsoj8y2fWybK5zbNlB1pRhPgoW_ob-vQ7uSkei4OV2lhbbqhP0nHUC/exec",
  studyVersion:"short-pilot-1.1-ai-only",
  prolificCompletionCode:"CTT26OSA",
  conditionMode:"AI_ONLY",
  conditionPools:{
    AI_ONLY:{means:["AI"],perspectives:["SELF","OTHER"]},
    FULL_2X3:{means:["AI","EXPERT","ALONE"],perspectives:["SELF","OTHER"]}
  }
};

const ITEMS=[
  ["J1","{Help} gave this person a starting point that they then built on.","{Help} gave me a starting point that I then built on.","help"],
  ["J2","This person used {help} to sharpen their own thinking.","I used {help} to sharpen my own thinking.","help"],
  ["J3","This person stayed in control and used {help} as support.","I stayed in control and used {help} as support.","help"],
  ["J4","This person knew what they wanted and used {help} to get there faster.","I knew what I wanted and used {help} to get there faster.","help"],
  ["K1","This person handed the real work over to {help}.","I handed the real work over to {help}.","help"],
  ["K2","{Help} did the thinking and this person just collected the result.","{Help} did the thinking and I just collected the result.","help"],
  ["K3","This person used {help} to avoid doing the task themselves.","I used {help} to avoid doing the task myself.","help"],
  ["K4","If you took {help} away, there would be very little of this person left in the result.","If you took {help} away, there would be very little of me left in the result.","help"],
  ["G1","This person put real effort into this.","I put real effort into this."],
  ["G2","Getting this done still demanded genuine effort from this person.","Getting this done still demanded genuine effort from me."],
  ["G3_R","This person took the easy way out.","I took the easy way out."],
  ["G4_R","This person was lazy about this.","I was lazy about this."],
  ["CR1","The good ideas in this came from this person.","The good ideas in this came from me."],
  ["CR2","This person shaped the result into something of their own.","I shaped the result into something of my own."],
  ["CR3_R","Anyone {method} would have ended up with much the same thing.","Anyone {method} would have ended up with much the same thing."],
  ["A1","This person is genuinely skilled at this kind of task.","I am genuinely skilled at this kind of task."],
  ["A2","This person could produce work of this standard on their own.","I could produce work of this standard on my own."],
  ["A3_R","This person lacks the competence to handle this task properly.","I lack the competence to handle this task properly."],
  ["A4_R","Whatever ability is on display here really belongs to {help}, not to this person.","Whatever ability is on display here really belongs to {help}, not to me.","help"],
  ["B1","This person is willing to put in real work when it matters.","I am willing to put in real work when it matters."],
  ["B2","This person cares about doing things properly.","I care about doing things properly."],
  ["B3_R","This person is the type to cut corners.","I am the type to cut corners."],
  ["C1","This person is sincere.","I am sincere."],
  ["C2","This person is someone of good character.","I am someone of good character."],
  ["C3_R","This person treats this as a purely transactional matter.","I treat this as a purely transactional matter."],
  ["D1","This person's expertise here is credible.","My expertise here is credible."],
  ["D2","This person's work can be depended on.","My work can be depended on."],
  ["D3_R","The reliability of this person's work is questionable.","The reliability of my work is questionable."],
  ["E1","The work this person produced is high quality.","The work I produced is high quality."],
  ["E2","This person's work is technically well done.","My work is technically well done."],
  ["E3_R","This person's final product falls short.","My final product falls short."]
];

const app=document.querySelector("#app"),progressLabel=document.querySelector("#progressLabel"),query=new URLSearchParams(location.search);
let state={participantId:crypto.randomUUID(),prolificPid:query.get("PROLIFIC_PID")||"",prolificStudyId:query.get("STUDY_ID")||"",prolificSessionId:query.get("SESSION_ID")||"",startedAt:null,condition:null,demographics:{},responses:{},timings:{},openedAt:Date.now(),pageOpenedAt:null,timingKey:null,itemOrder:[]};

function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));}
function shuffle(a){const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]];}return b;}
function setProgress(n){progressLabel.textContent=String(n).padStart(2,"0")+" / 04";}
function beginTiming(k){state.timingKey=k;state.pageOpenedAt=Date.now();}
function endTiming(){if(state.timingKey){state.timings[`time_${state.timingKey}_sec`]=Number(((Date.now()-state.pageOpenedAt)/1000).toFixed(3));state.timingKey=null;}}
function randomCondition(){const pool=CONFIG.conditionPools[CONFIG.conditionMode];if(!pool)throw new Error(`Unknown condition mode: ${CONFIG.conditionMode}`);return {scenario:"S3",means:pool.means[Math.floor(Math.random()*pool.means.length)],perspective:pool.perspectives[Math.floor(Math.random()*pool.perspectives.length)]};}
function helpLabel(cap=false){let h=state.condition.means==="AI"?"the AI":"the presentation consultant";return cap?h[0].toUpperCase()+h.slice(1):h;}
function vignette(){const self=state.condition.perspective==="SELF";let means=state.condition.means==="AI"?"with the help of an AI tool (such as ChatGPT)":state.condition.means==="EXPERT"?"with the help of a professional presentation consultant":self?"entirely on your own, without any help":"entirely on their own, without any help";return self?`Imagine that you need to prepare the slides and talking points for an important work presentation. You complete it ${means}.`:`Imagine you observe someone — an ordinary person, much like you — who needs to prepare the slides and talking points for an important work presentation. They complete it ${means}.`;}
function itemText(item){const method=state.condition.means==="AI"?"using the same tool":state.condition.means==="EXPERT"?"working with the same presentation consultant":"completing the task without help";return item[state.condition.perspective==="SELF"?2:1].replaceAll("{help}",helpLabel()).replaceAll("{Help}",helpLabel(true)).replaceAll("{method}",method);}
function field(name,label,type,extra=""){return `<div class="field"><label for="${name}">${label}</label><input id="${name}" name="${name}" type="${type}" ${extra}></div>`;}
function select(name,label,options){return `<div class="field"><label for="${name}">${label}</label><select id="${name}" name="${name}" required><option value="">Select an option</option>${options.map(x=>`<option>${x}</option>`).join("")}</select></div>`;}
function configureEnglishValidation(form){form.querySelectorAll("input,select").forEach(control=>{const clear=()=>control.setCustomValidity("");control.addEventListener("input",clear);control.addEventListener("change",clear);control.addEventListener("invalid",()=>{control.setCustomValidity("");if(control.validity.valueMissing)control.setCustomValidity(control.tagName==="SELECT"?"Please select an option.":"Please complete this field.");else if(control.validity.rangeUnderflow||control.validity.rangeOverflow||control.validity.stepMismatch)control.setCustomValidity("Please enter a whole number between 18 and 100.");else if(control.validity.tooLong)control.setCustomValidity("Please shorten this response.");else control.setCustomValidity("Please enter a valid response.");});});}

function start(){if(!state.prolificPid){setProgress(0);app.innerHTML=`<section class="status-card panel"><p class="section-code">Cannot start study</p><h1>Missing Prolific participant ID.</h1><p class="lede">Please open this study using the link provided by Prolific.</p><p class="hint">For researcher testing, append <code>?PROLIFIC_PID=TEST</code> to the page address.</p></section>`;return;}state.startedAt=new Date().toISOString();state.condition=randomCondition();const eligible=ITEMS.filter(x=>state.condition.means!=="ALONE"||x[3]!=="help");state.itemOrder=shuffle(eligible.map(x=>x[0]));renderDemographics();}
function renderDemographics(){setProgress(1);beginTiming("demographics");app.innerHTML=`<section class="panel"><p class="section-code">01 / Background</p><h1>First, a little about you.</h1><form id="demoForm" class="form-grid">${field("age","Age","number",'min="18" max="100" step="1" required')}${select("gender","Gender",["Woman","Man","Other / Prefer not to say"])}${select("education","Highest level of education completed",["Primary or lower secondary","Upper secondary","Vocational qualification","Bachelor’s degree","Master’s degree","Doctoral degree","Other","Prefer not to say"])}${select("employment","Current employment status",["Employed full-time","Employed part-time","Self-employed","Student","Not currently employed","Retired","Other","Prefer not to say"])}${select("country","Country of residence",["United Kingdom","United States","Ireland","Australia","Other"])}${select("native_language","First language",["English","Other"])}<div class="actions field full"><button class="button primary">Continue <span>→</span></button></div></form></section>`;const form=document.querySelector("#demoForm");configureEnglishValidation(form);form.onsubmit=e=>{e.preventDefault();endTiming();state.demographics=Object.fromEntries(new FormData(e.target));renderVignette();};}
function renderVignette(){setProgress(2);beginTiming("vignette");app.innerHTML=`<section class="panel"><p class="section-code">02 / Situation</p><h1>Imagine the following situation in detail.</h1><div class="vignette deliberating">${escapeHtml(vignette())}</div><div class="deliberation-guide"><p class="instruction">For the next 30 seconds, form a vivid mental picture of the situation. Keep it in mind when answering the questions.</p><div class="countdown" id="countdown">0:30</div></div><div class="actions"><button class="button primary" id="toItems" disabled>Continue in 30s <span>→</span></button></div></section>`;let remaining=30;const button=document.querySelector("#toItems"),counter=document.querySelector("#countdown"),timer=setInterval(()=>{remaining--;counter.textContent=`0:${String(remaining).padStart(2,"0")}`;button.firstChild.textContent=`Continue in ${remaining}s `;if(remaining<=0){clearInterval(timer);counter.textContent="READY";button.disabled=false;button.firstChild.textContent="Continue ";}},1000);button.onclick=()=>{endTiming();renderItems();};}
function scaleItem(item){return `<div class="question" data-item="${item[0]}"><p class="question-text">${escapeHtml(itemText(item))}</p><div class="scale" role="radiogroup" aria-label="Agreement scale">${[1,2,3,4,5,6,7].map(n=>`<label><input type="radio" name="${item[0]}" value="${n}" required><span>${n}</span></label>`).join("")}</div><div class="anchors"><span>Strongly disagree</span><span>Neither</span><span>Strongly agree</span></div></div>`;}
function renderItems(){setProgress(3);beginTiming("items");app.innerHTML=`<section class="study-layout panel"><aside class="scenario-rail"><p class="section-code">Situation</p><h2 class="scenario-heading">Keep this situation in mind</h2><div class="vignette">${escapeHtml(vignette())}</div><p class="instruction">Base every response on this exact situation.</p></aside><div class="section-pane"><p class="section-code">Your assessment</p><h1>How do you see this situation?</h1><div id="itemCarousel" class="item-carousel" aria-live="polite"></div><div class="item-progress-meta"><span id="itemProgressText"></span></div><div class="item-progress-track" role="progressbar" aria-label="Question progress" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div id="itemProgressFill"></div></div></div></section>`;renderCarouselItem(0);}
function renderCarouselItem(index){if(index>=state.itemOrder.length){endTiming();renderFinal();return;}const map=new Map(ITEMS.map(x=>[x[0],x])),id=state.itemOrder[index],total=state.itemOrder.length,carousel=document.querySelector("#itemCarousel"),progress=document.querySelector(".item-progress-track"),fill=document.querySelector("#itemProgressFill");document.querySelector("#itemProgressText").textContent=`Question ${index+1} of ${total}`;const pct=Math.round(index/total*100);progress.setAttribute("aria-valuenow",String(pct));fill.style.width=`${pct}%`;carousel.innerHTML=scaleItem(map.get(id));carousel.querySelectorAll('input[type="radio"]').forEach(input=>input.addEventListener("change",()=>{state.responses[id]=input.value;carousel.querySelectorAll('input[type="radio"]').forEach(x=>x.disabled=true);const answeredPct=Math.round((index+1)/total*100);progress.setAttribute("aria-valuenow",String(answeredPct));fill.style.width=`${answeredPct}%`;setTimeout(()=>renderCarouselItem(index+1),220);},{once:true}));}
function renderFinal(){setProgress(4);beginTiming("final");app.innerHTML=`<section class="panel"><p class="section-code">Final questions</p><h1>Almost finished.</h1><form id="finalForm" class="form-grid">${select("ai_frequency","How often do you use generative AI tools such as ChatGPT?",["Never","Less than monthly","Monthly","Weekly","Several times a week","Daily or almost daily"])}${select("study_guess","What do you think this study was mainly about?",["Evaluations of work and the people who produce it","Memory for written information","Preferences for different kinds of tasks","I am not sure","Other"])}<div class="field full"><label for="comment">Optional comments</label><input id="comment" name="comment" maxlength="500"><span class="hint">Do not include identifying information.</span></div><div class="actions field full"><button class="button primary">Submit responses <span>→</span></button></div></form></section>`;const form=document.querySelector("#finalForm");configureEnglishValidation(form);form.onsubmit=async e=>{e.preventDefault();endTiming();Object.assign(state.responses,Object.fromEntries(new FormData(e.target)));state.timings.time_total_sec=Number(((Date.now()-state.openedAt)/1000).toFixed(3));await submit(e.target.querySelector("button"));};}
async function submit(button){button.disabled=true;button.textContent="Submitting…";const payload={participant_id:state.participantId,study_version:CONFIG.studyVersion,started_at:state.startedAt,completed_at:new Date().toISOString(),scenario:state.condition.scenario,means:state.condition.means,perspective:state.condition.perspective,item_order:state.itemOrder.join("|"),...state.demographics,...state.responses,...state.timings,completed:1,prolific_pid:state.prolificPid,prolific_study_id:state.prolificStudyId,prolific_session_id:state.prolificSessionId};try{if(!CONFIG.endpoint){const blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`short-pilot-${state.participantId}.json`;a.click();renderThanks(true);return;}const res=await fetch(CONFIG.endpoint,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(payload)}),out=await res.json();if(!res.ok||!out.ok)throw new Error(out.error||"Save failed");renderThanks(false);}catch(_){button.disabled=false;button.textContent="Try submitting again →";document.querySelector("#finalForm").insertAdjacentHTML("beforeend",'<div class="error-summary field full">We could not save your responses. Please check your connection and try again.</div>');}}
function renderThanks(test){const configured=CONFIG.prolificCompletionCode;app.innerHTML=`<section class="status-card panel"><div class="status-mark">✓</div><p class="section-code">Study complete</p><h1 class="completion-heading">Thank you for taking part.</h1><p class="lede completion-lede">Your responses ${test?"were downloaded as a local test file":"have been recorded"}.</p><div class="rule"></div><h2>About this study</h2><div class="prose"><p>You were randomly asked to consider a work presentation completed with AI assistance, from either a self or observer perspective.</p><p>The study examines how this perspective affects judgments of effort, creativity, competence, character, reliability, and work quality.</p></div>${!test&&configured?`<div class="actions"><a class="button primary" href="https://app.prolific.com/submissions/complete?cc=${encodeURIComponent(configured)}">Return to Prolific <span>→</span></a></div>`:""}</section>`;}
start();
